export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Home } from "./Home";
export { default as User } from "./User";
export { default as Clinics } from "./Clinics";
export { default as SingleClinic } from "./SingleClinic";
export { default as Appointements } from "./Appointements";
export { default as Vets } from "./Vets";
export { default as SingleVet } from "./SingleVet";